const fs=require('fs'),assert=require('node:assert/strict'),test=require('node:test'),vm=require('node:vm');
const html=fs.readFileSync('app/static/index.html','utf8');
const inline=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)].at(-1)[1];
function pure(){const end=inline.indexOf('function renderPhaseStepper');const payload=inline.match(/function buildExperimentPayload\([^]*?\n\}/)[0];const src='var MAX_SCIENTIFIC_POINTS=10000;\n'+inline.slice(inline.indexOf('function field'),end)+'\n'+payload;const c={Number,Math,JSON};vm.createContext(c);vm.runInContext(src,c);return c}
const plain=x=>JSON.parse(JSON.stringify(x));
function integrationHarness(){
  const elements=new Map(), requests=[];
  function leaf(){return {innerText:'',textContent:'',style:{},className:'',setAttribute(){},removeAttribute(){},focus(){}}}
  function element(id=''){const attrs={},listeners={};return {id,value:id==='experimentMode'?'FIXED_TEMPERATURE':'',innerText:'',textContent:'',hidden:false,disabled:false,style:{display:'none'},dataset:{},children:[],cells:Array.from({length:5},leaf),classList:{add(){},remove(){},toggle(){}},appendChild(x){this.children.push(x);return x},append(...x){this.children.push(...x)},replaceChildren(...x){this.children=x},querySelector(){return element()},focus(){},addEventListener(type,fn){listeners[type]=fn},click(){listeners.click&&listeners.click()},getContext(){return {}},setAttribute(k,v){attrs[k]=String(v)},removeAttribute(k){delete attrs[k]},getAttribute(k){return attrs[k]??null}}}
  const channelButtons=['ir','tc','lux','setpoint'].map(channel=>{const b=element('toggle'+channel);b.dataset.channel=channel;b.setAttribute('aria-pressed','true');return b});
  const document={activeElement:null,getElementById(id){if(!elements.has(id))elements.set(id,element(id));return elements.get(id)},createElement:t=>element(t),createTextNode:t=>({textContent:t}),querySelector:()=>element(),querySelectorAll:selector=>selector==='[data-channel]'?channelButtons:[],addEventListener(){}};
  class Chart{static register(){} constructor(ctx,config){this.data=config.data;this.options=config.options;this.ctx={save(){},restore(){},fillRect(){}};this.scales={x:{getPixelForValue:x=>x}};this.chartArea={top:0,bottom:100}} update(){} destroy(){} resetZoom(){}}
  const context={document,Chart,console,Date,Math,JSON,Number,parseInt,parseFloat,Promise,fetch:(url,opts)=>{if(url==='/api/get_config')return Promise.resolve({ok:true,json:async()=>({})});requests.push({url,opts});return Promise.resolve({ok:true,json:async()=>url==='/api/start_experiment'?{status:'success',id:1}:{}})},setInterval(){},clearInterval(){},setTimeout(fn){fn()},clearTimeout(){},alert(){throw Error('live DOM validation called')}};
  context.window=context;vm.createContext(context);vm.runInContext(inline,context);return {c:context,elements,requests};
}
const tick=()=>new Promise(r=>setImmediate(r));
test('real updateStatus integration synchronizes cached idle/running telemetry into both charts',async()=>{const h=integrationHarness(),c=h.c;let calls=0,original=c.appendScientificSample;c.appendScientificSample=function(...a){calls++;return original(...a)};const samples=[{total_time:1,ir_temp:31,tc_temp:30,current_lux:100,state_code:9,temp_setpoint:40},{total_time:2,ir_temp:32,tc_temp:31,current_lux:110,state_code:10,temp_setpoint:40}];c.fetch=async()=>({ok:true,json:async()=>({active_experiment:{status:'IDLE',mode:'FIXED_TEMPERATURE',temperature_tolerance:1,max_temp:90,target_lux:120},recent_data:samples})});c.updateStatus();await tick();await tick();assert.equal(calls,2);assert.equal(c.scientificSeries.samples.length,2);assert.equal(c.chart.data.datasets[0].data.length,2);assert.equal(c.luxChart.data.datasets[0].data.length,2);assert.equal(c.chart.options.plugins.phaseRegions.regions.length,2);c.updateStatus();await tick();await tick();assert.equal(c.scientificSeries.samples.length,2,'cached idle response dedupes');c.isRunning=true;c.lastPlottedTime=-1;c.updateStatus();await tick();await tick();assert.equal(c.scientificSeries.samples.length,2,'cached running response dedupes');assert.equal(calls,6,'handler routes every candidate through append exactly once')});
test('confirm validates only immutable snapshot, not mutated DOM',async()=>{const h=integrationHarness(),c=h.c,p={operator_name:'A',sample_name:'snapshot',duration:60,cycles:1,max_temp:90,target_lux:10,interval:1};c.pendingReviewPayload=p;c.document.getElementById('sampleName').value='';c.document.getElementById('maxTemp').value='0';c.confirmReviewedStart();await tick();await tick();assert.equal(h.requests[0].url,'/api/start_experiment');assert.deepEqual(JSON.parse(h.requests[0].opts.body),p)});
test('review snapshot is immutable and validation precedes review',()=>{const c=pure(),v={operator_name:'A',sample_name:'S',duration:60,cycles:2,max_temp:100,target_lux:3,interval:1,mode:'NORMAL_CYCLIC'};let m=c.buildReviewModel(v);v.sample_name='MUTATED';assert.equal(m.payload.sample_name,'S');assert.equal(c.validateSetupValues({...v,operator_name:''}), 'Operator and sample name are required.');assert.equal(c.validateSetupValues(v),null);assert.match(inline,/startExperiment\(payload\)/);assert.match(inline,/var payload=JSON\.parse\(JSON\.stringify\(pendingReviewPayload\)\)/)});
test('bounded synchronized samples, stable dedupe, and reset',()=>{const c=pure(),b=c.emptyScientificSeries();for(let i=0;i<c.MAX_SCIENTIFIC_POINTS+2;i++)c.appendScientificSample(b,{total_time:i,ir_temp:i,tc_temp:i+1,current_lux:i+2,state_code:i%2,temp_setpoint:i}, {target_lux:50,max_temp:90},'FIXED_TEMPERATURE');assert.equal(b.samples.length,c.MAX_SCIENTIFIC_POINTS);assert.equal(b.samples[0].x,2);assert.equal(c.appendScientificSample(b,{total_time:c.MAX_SCIENTIFIC_POINTS+1,ir_temp:c.MAX_SCIENTIFIC_POINTS+1,tc_temp:c.MAX_SCIENTIFIC_POINTS+2,current_lux:c.MAX_SCIENTIFIC_POINTS+3,state_code:(c.MAX_SCIENTIFIC_POINTS+1)%2,temp_setpoint:c.MAX_SCIENTIFIC_POINTS+1},{target_lux:50},'FIXED_TEMPERATURE'),false);assert.deepEqual(plain(c.emptyScientificSeries()),{samples:[]})});
test('timestamped overlays never backfill and plateau begins when detected',()=>{const c=pure(),b=c.emptyScientificSeries();c.appendScientificSample(b,{total_time:1,ir_temp:1,tc_temp:2,current_lux:3,state_code:9,temp_setpoint:50},{temperature_tolerance:1,max_temp:90,target_lux:10},'FIXED_TEMPERATURE');c.appendScientificSample(b,{total_time:2,ir_temp:2,tc_temp:3,current_lux:4,state_code:10,temp_setpoint:55},{temperature_tolerance:1,max_temp:90,target_lux:20},'FIXED_TEMPERATURE');assert.deepEqual(plain(b.samples.map(x=>x.setpoint)),[50,55]);assert.deepEqual(plain(b.samples.map(x=>x.toleranceLower)),[49,54]);let p=c.emptyScientificSeries();c.appendScientificSample(p,{total_time:1,state_code:12},{},'NATURAL_PLATEAU');c.appendScientificSample(p,{total_time:2,state_code:13,detected_plateau_temp:42},{},'NATURAL_PLATEAU');assert.deepEqual(plain(p.samples.map(x=>x.plateau)),[null,42])});
test('windows derive identical synchronized views and Live is latest 60 seconds',()=>{const c=pure(),b={samples:[0,30,90].map(x=>({x,ir:x,tc:x,lux:x}))};assert.deepEqual(c.selectScientificView(b,'live').map(x=>x.x),[30,90]);assert.deepEqual(c.selectScientificView(b,'1m').map(x=>x.x),[30,90]);assert.equal(c.selectScientificView(b,'all').length,3);assert.match(html,/Live \(latest 60s\)/)});
test('phase regions use actual contiguous transitions',()=>{const c=pure(),r=c.derivePhaseRegions([{x:0,stateCode:9},{x:2,stateCode:9},{x:3,stateCode:10},{x:5,stateCode:11}], 'FIXED_TEMPERATURE');assert.deepEqual(plain(r.map(x=>[x.start,x.end,x.label])),[[0,3,'Ramp'],[3,5,'Qualify'],[5,5,'Hold']]);assert.match(inline,/phaseRegions.*regions/)});
test('target lux is timestamped only when available',()=>{const c=pure(),b=c.emptyScientificSeries();c.appendScientificSample(b,{total_time:1,current_lux:4},{},'NORMAL_CYCLIC');c.appendScientificSample(b,{total_time:2,current_lux:5},{target_lux:20},'NORMAL_CYCLIC');assert.deepEqual(plain(b.samples.map(x=>x.targetLux)),[null,20])});
test('summary uses protocol-supported fields with units and em dash',()=>{const c=pure();assert.deepEqual(plain(c.buildResultSummary('FIXED_TEMPERATURE',{}, {control_temp:40,temp_error:-1,hold_qualified_elapsed_s:5,lamp_pwm:120,current_lux:44})),{control:'40 °C',error:'-1 °C',hold_elapsed:'5 s',lamp_pwm:'120 / 255',current_lux:'44 lx'});let p=c.buildResultSummary('NATURAL_PLATEAU',{},{});assert.equal(p.detected_plateau,'—');assert.ok(!('slope' in p));assert.ok(!('range' in p));assert.ok(!('confirmation' in p))});
test('production control/focus wiring exists and dataset mapping is named',()=>{for(const s of ["querySelectorAll('[data-window]')","applyChartView()","data-channel","handleReviewModalKeydown","reviewModalOpener","aria-pressed","DATASET_INDEX"])assert.ok(inline.includes(s),s);assert.match(inline,/function resetZoom\(\)[^]*?applyChartView\(\)/)});
test('reset preserves button-driven channel visibility and aria state on recreated charts',()=>{const {c}=integrationHarness(),buttons=c.document.querySelectorAll('[data-channel]'),byChannel=channel=>buttons.find(b=>b.dataset.channel===channel);byChannel('ir').click();byChannel('lux').click();byChannel('setpoint').click();assert.equal(byChannel('ir').getAttribute('aria-pressed'),'false');assert.equal(byChannel('lux').getAttribute('aria-pressed'),'false');assert.equal(byChannel('setpoint').getAttribute('aria-pressed'),'false');const oldChart=c.chart,oldLux=c.luxChart;c.resetChartData();assert.notEqual(c.chart,oldChart);assert.notEqual(c.luxChart,oldLux);assert.equal(c.chart.data.datasets[c.DATASET_INDEX.IR].hidden,true);assert.equal(c.chart.data.datasets[c.DATASET_INDEX.TC].hidden,false);for(const i of [c.DATASET_INDEX.TOLERANCE_LOWER,c.DATASET_INDEX.TOLERANCE_UPPER,c.DATASET_INDEX.SETPOINT,c.DATASET_INDEX.SAFETY,c.DATASET_INDEX.PLATEAU])assert.equal(c.chart.data.datasets[i].hidden,true);assert.equal(c.luxChart.data.datasets[0].hidden,true);assert.equal(byChannel('ir').getAttribute('aria-pressed'),'false');assert.equal(byChannel('lux').getAttribute('aria-pressed'),'false');assert.equal(byChannel('setpoint').getAttribute('aria-pressed'),'false');assert.equal(c.chart.data.datasets.length,7);assert.equal(c.luxChart.data.datasets.length,2)});
new Function(inline);
